<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

    // Define the fillable attributes
    protected $fillable = [
        'type',
        'generated_by',
        'data',
    ];

    // Relationship with User (assuming reports are generated by users)
    public function user()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}